/**
 * Seed Script for Firestore Listings
 *
 * Run this once to populate your database with sample listings.
 *
 * Usage: npx ts-node scripts/seedListings.ts
 * Or copy the data objects and paste into Firestore Console manually.
 */

// Sample Villas Data
export const sampleVillas = [
  {
    name: "Modern Waterfront Villa",
    location: "Miami",
    description: "Stunning modern waterfront villa with private dock and infinity pool. Perfect for luxury getaways.",
    pricePerNight: 2800,
    bedrooms: 5,
    bathrooms: 5,
    maxGuests: 10,
    amenities: ["Pool", "Chef", "Ocean View", "Private Dock", "Gym"],
    images: ["/placeholder-villa.jpg"],
    provider: "shift_fleet",
    providerId: "manual_v1",
    source: "manual",
    blockedDates: [],
    minimumStay: 3,
    status: "active",
    featured: true,
  },
  {
    name: "Coconut Grove Waterfront",
    location: "Miami",
    description: "Beautiful waterfront property in the heart of Coconut Grove with stunning bay views.",
    pricePerNight: 3400,
    bedrooms: 6,
    bathrooms: 6,
    maxGuests: 12,
    amenities: ["Waterfront", "Dock", "Pool", "Chef Available"],
    images: ["/placeholder-villa.jpg"],
    provider: "shift_fleet",
    providerId: "manual_v2",
    source: "manual",
    blockedDates: [],
    minimumStay: 3,
    status: "active",
    featured: true,
  },
  {
    name: "Star Island Mansion",
    location: "Miami",
    description: "Exclusive Star Island estate with panoramic views and world-class amenities.",
    pricePerNight: 5500,
    bedrooms: 7,
    bathrooms: 8,
    maxGuests: 14,
    amenities: ["Pool", "Tennis Court", "Private Beach", "Chef", "Security"],
    images: ["/placeholder-villa.jpg"],
    provider: "shift_fleet",
    providerId: "manual_v3",
    source: "manual",
    blockedDates: [],
    minimumStay: 5,
    status: "active",
    featured: true,
  },
  {
    name: "Hollywood Hills Retreat",
    location: "LA",
    description: "Iconic Hollywood Hills home with breathtaking city views and modern architecture.",
    pricePerNight: 3100,
    bedrooms: 5,
    bathrooms: 5,
    maxGuests: 10,
    amenities: ["Pool", "City View", "Chef", "Home Theater"],
    images: ["/placeholder-villa.jpg"],
    provider: "shift_fleet",
    providerId: "manual_v4",
    source: "manual",
    blockedDates: [],
    minimumStay: 3,
    status: "active",
    featured: false,
  },
  {
    name: "Central Park Penthouse",
    location: "NYC",
    description: "Ultra-luxury penthouse overlooking Central Park with wraparound terrace.",
    pricePerNight: 4800,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    amenities: ["Park View", "Concierge", "Terrace", "Gym Access"],
    images: ["/placeholder-villa.jpg"],
    provider: "shift_fleet",
    providerId: "manual_v5",
    source: "manual",
    blockedDates: [],
    minimumStay: 2,
    status: "active",
    featured: true,
  },
];

// Sample Cars Data
export const sampleCars = [
  {
    name: "Lamborghini Urus",
    brand: "Lamborghini",
    model: "Urus",
    location: "Miami",
    description: "The world's first Super Sport Utility Vehicle. Experience unmatched performance and luxury.",
    pricePerDay: 1200,
    bodyStyle: "SUV",
    seats: 4,
    power: "641 HP",
    images: ["/placeholder-car.jpg"],
    provider: "shift_fleet",
    providerId: "manual_c1",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: true,
  },
  {
    name: "Rolls Royce Ghost",
    brand: "Rolls Royce",
    model: "Ghost",
    location: "Miami",
    description: "The pinnacle of luxury sedans. Whisper-quiet and supremely comfortable.",
    pricePerDay: 950,
    bodyStyle: "Sedan",
    seats: 4,
    power: "563 HP",
    images: ["/placeholder-car.jpg"],
    provider: "shift_fleet",
    providerId: "manual_c2",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: true,
  },
  {
    name: "Ferrari 488 Spider",
    brand: "Ferrari",
    model: "488 Spider",
    location: "Miami",
    description: "Open-top supercar thrills with Ferrari's legendary V8 power.",
    pricePerDay: 1500,
    bodyStyle: "Convertible",
    seats: 2,
    power: "661 HP",
    images: ["/placeholder-car.jpg"],
    provider: "shift_fleet",
    providerId: "manual_c3",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: true,
  },
  {
    name: "McLaren 720S",
    brand: "McLaren",
    model: "720S",
    location: "LA",
    description: "British engineering excellence. Breathtaking performance and design.",
    pricePerDay: 1800,
    bodyStyle: "Coupe",
    seats: 2,
    power: "710 HP",
    images: ["/placeholder-car.jpg"],
    provider: "shift_fleet",
    providerId: "manual_c4",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: true,
  },
  {
    name: "Mercedes-AMG G63",
    brand: "Mercedes-Benz",
    model: "AMG G63",
    location: "NYC",
    description: "Iconic design meets AMG performance. Luxury SUV perfection.",
    pricePerDay: 750,
    bodyStyle: "SUV",
    seats: 5,
    power: "577 HP",
    images: ["/placeholder-car.jpg"],
    provider: "shift_fleet",
    providerId: "manual_c5",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: false,
  },
];

// Sample Yachts Data
export const sampleYachts = [
  {
    name: "Azure Horizon 85ft",
    length: 85,
    location: "Miami",
    description: "Luxurious 85ft yacht perfect for day charters and sunset cruises in Miami.",
    pricePerHour: 1200,
    maxGuests: 12,
    crewIncluded: true,
    amenities: ["Captain", "Chef", "Jet Skis", "Snorkeling Gear"],
    images: ["/placeholder-yacht.jpg"],
    provider: "shift_fleet",
    providerId: "manual_y1",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: true,
  },
  {
    name: "Sunset Cruiser 65ft",
    length: 65,
    location: "Miami",
    description: "Perfect yacht for intimate gatherings and Miami sunset experiences.",
    pricePerHour: 850,
    maxGuests: 10,
    crewIncluded: true,
    amenities: ["Crew", "Open Bar", "Snorkeling", "Sound System"],
    images: ["/placeholder-yacht.jpg"],
    provider: "shift_fleet",
    providerId: "manual_y2",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: false,
  },
  {
    name: "Pacific Majesty 90ft",
    length: 90,
    location: "LA",
    description: "Experience the California coast aboard this stunning 90ft vessel.",
    pricePerHour: 1800,
    maxGuests: 16,
    crewIncluded: true,
    amenities: ["Captain", "Chef", "Diving Gear", "Tender"],
    images: ["/placeholder-yacht.jpg"],
    provider: "shift_fleet",
    providerId: "manual_y3",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: true,
  },
  {
    name: "Hudson Elite 70ft",
    length: 70,
    location: "NYC",
    description: "Cruise the Hudson River and enjoy Manhattan skyline views.",
    pricePerHour: 950,
    maxGuests: 12,
    crewIncluded: true,
    amenities: ["Captain", "Catering", "Skyline Views", "Climate Control"],
    images: ["/placeholder-yacht.jpg"],
    provider: "shift_fleet",
    providerId: "manual_y4",
    source: "manual",
    blockedDates: [],
    status: "active",
    featured: true,
  },
];

console.log("=== SAMPLE DATA FOR FIRESTORE ===");
console.log("\nCopy these into Firestore Console or use Firebase Admin SDK to seed.\n");
console.log("Villas:", JSON.stringify(sampleVillas, null, 2));
console.log("\nCars:", JSON.stringify(sampleCars, null, 2));
console.log("\nYachts:", JSON.stringify(sampleYachts, null, 2));
